### ISSUE TITLE
cat *.min.js

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/where-is-firefox-os#13]
cc @cvan

**Comment by nickdesaulniers** [comment]
while clever, this will not work for linear dependency chains unless the dependents are lower in alphabetical order.  Such a naming scheme to preserve the build system is brittle and not worth it.

**Comment by cvan** [comment]
yeah if you do classic AMD, this would work. otherwise, you'd want to use something like browserify (which is arguably overkill for this project).
