### ISSUE TITLE
broken in Safari

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/where-is-firefox-os#17]
I think safari doesn't understand `xhr.responseType = 'json';` as xhr.response is still a string?

**Comment by nickdesaulniers** [comment]
@cvan @potch , you guys know anything about this?

**Comment by cvan** [comment]
Which version of Safari are you running? WFM. According to [caniuse](http://caniuse.com/#feat=xhr2), XHR 2 is pretty much everywhere except Opera Mini and IE 9 and lower.

**Comment by cvan** [comment]
And looks like specifically `json` `responseType` was added to WebKit in [2013](https://bugs.webkit.org/show_bug.cgi?id=73648).

**Comment by nickdesaulniers** [comment]
Version 6.1.6 (8537.78.2)

**Comment by nickdesaulniers** [comment]
Just upgraded to 6.2.  Works.
